# Database Properties
db.driver=org.h2.Driver
db.url=jdbc:h2:mem:ameerrasikmart;DB_CLOSE_DELAY=-1;MODE=MySQL
db.username=sa
db.password=
db.pool.max-size=10
db.pool.min-idle=2
db.pool.connection-timeout=30000

# Security Properties
security.session.timeout.minutes=30
